;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dired-maybe-insert-subdir
        mark-sexp
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        ))
