# Screen mirroring setup for sway using wlr-mirror
# Dependency: https://github.com/Ferdi265/wl-mirror

mode "present" {
    # command starts mirroring
    bindsym m mode "default"; exec ~/opt/wl-present mirror
    # these commands modify an already running mirroring window
    bindsym o mode "default"; exec ~/opt/wl-present set-output
    bindsym r mode "default"; exec ~/opt/wl-present set-region
    bindsym Shift+r mode "default"; exec ~/opt/wl-present unset-region
    bindsym s mode "default"; exec ~/opt/wl-present set-scaling
    bindsym f mode "default"; exec ~/opt/wl-present toggle-freeze
    bindsym c mode "default"; exec ~/opt/wl-present custom

    # return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+p mode "present"