### Input configuration
#
# Example configuration:
#
input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
    pointer_accel 0.8
}

input type:keyboard {
    repeat_rate 100
    repeat_delay 300
}

input type:pointer {
    accel_profile adaptive
    scroll_factor 1.5
    pointer_accel 0
}
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.

