# Picture in picture setting for swaywm

for_window [title="Picture-in-Picture"] floating enable, sticky enable, move position center
for_window [window_role="PictureInPicture"] floating enable, sticky enable
