# Dependency: https://github.com/coffeeispower/woomer
#
bindsym $mod+x exec ~/.local/bin/woomer

mode "screenshot" {
    bindsym s exec grimshot --notify savecopy area; mode "default"
    bindsym Shift+s exec grimshot --notify save area; mode "default"
    bindsym Control+s exec grimshot --notify save active; mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+s mode "screenshot"
