;;; uxntal-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uxntal-mode.el

(add-to-list 'auto-mode-alist '("\\.tal\\'" . uxntal-mode))
(autoload 'uxntal-mode "uxntal-mode" "\
Major mode for editing Uxntal files.

(fn)" t)
(register-definition-prefixes "uxntal-mode" '("uxntal-"))

;;; End of scraped data

(provide 'uxntal-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uxntal-mode-autoloads.el ends here
