;;; cobol-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cobol-mode.el

(autoload 'cobol-mode "cobol-mode" "\
COBOL mode is a major mode for handling COBOL files.

(fn)" t)
(register-definition-prefixes "cobol-mode" '("cobol-"))

;;; End of scraped data

(provide 'cobol-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cobol-mode-autoloads.el ends here
