font_size 13

cursor_shape block

editor nvim
foreground #ffffff
# background #000000

sync_to_monitor yes

window_border_width 0.5pt

window_margin_width 0

window_padding_width 1
# font_family      family="Comic Code"

enable_audio_bell no


# BEGIN_KITTY_FONTS
font_family      family="Comic Code"
# font_family      family="MartianMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Default
include current-theme.conf
# END_KITTY_THEME
