unbind C-b
set -g prefix C-x
bind C-x send-prefix
setw -g mouse on
set -g mode-keys emacs
set -g status-keys emacs
set -s escape-time 0
set -g status-style 'fg=yellow'
set -g status-right "%H:%M %d-%b-%y"
