;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        completion-at-point
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        amx
        beginning-of-buffer
        compile
        dired-do-rename
        mark-sexp
        multiple-cursors-mode
        paredit-semicolon
        wdired--self-insert
        ))
