;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        amx
        dired-mark
        elisp-byte-compile-file
        kill-region
        mark-sexp
        undo-redo
        ))

(setq mc/cmds-to-run-once
      '(
        compile
        paredit-RET
        toggle-input-method
        ))
